language: php

php:
    - 5.4
    - 5.5
    - 5.6

install:
    - composer self-update
    - composer install

before_script:
    - php -S localhost:8080 ./src-dev/public/index.php > /dev/null

script:
    - ./vendor/bin/behat --config tests/behat/behat.yml --suite blackbox --append-snippets;

after_script:
    - php vendor/bin/coveralls -v
